use_frameworks!

platform :ios, '8.0'

target 'LoginFormView_Example' do
  pod 'LoginFormView', :path => '../'

  target 'LoginFormView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
